name: sqliteflutter
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0
  flutter:
    sdk: flutter

  
  cupertino_icons: ^0.1.2
  sqflite: ^1.1.5
  path_provider: ^0.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  
  uses-material-design: true

  